language: node_js
node_js:
    - "6"

cache:
    directories:
        - "node_modules"

before_install:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm install -g serverless; fi

install:
    - npm install

before_script:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then serverless deploy -v --stage "travis-${TRAVIS_BUILD_ID}-${TRAVIS_BUILD_NUMBER}"; fi

script:
    - npm test

after_script:
    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then serverless remove -v --stage "travis-${TRAVIS_BUILD_ID}-${TRAVIS_BUILD_NUMBER}"; fi

    - npm install ocular.js
    - $(npm bin)/ocular coverage/clover.xml
