service: lambda-comments

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, env:AWS_DEFAULT_REGION, 'us-east-1'}

functions:
  hello:
    handler: src/handler.hello
  twitter_authenticate:
    handler: src/oauth/twitter.requestToken
    events:
      - http: GET twitter/authenticate
